kind: pipeline
type: docker
name: default

steps:
- name: 50ohm.de
  image: ghcr.io/astral-sh/uv:python3.12-bookworm
  environment:
  commands:
  - uv pip install --system --break-system-packages --requirements requirements.txt
  - pytest --junitxml=./test-reports/junit.xml 
