kind: pipeline
type: docker
name: default

steps:
- name: 50ohm.de
  image: debian:latest
  environment:
  commands:
  - apt-get update && apt-get install -qyf --no-install-recommends python3
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - pip install --break-system-packages `cat requirements.txt`
  - cd test && pytest